# Model parameters
model:
  max_input_length: 1024
  max_target_length: 256
  model_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"  # Add this if not in config.yaml

# Vector Database parameters
vector_db:
  chunk_size: 512
  chunk_overlap: 50

# Transcription parameters
transcription:
  chunk_length_s: 10
  batch_size: 1
  language: "en"
  return_timestamps: true

# LLM generation parameters
generation:
  max_new_tokens: 256
  temperature: 0.3
  top_p: 0.9
  repetition_penalty: 1.1
  
# Fine-tuning parameters
training:
  learning_rate: 2e-5
  warmup_steps: 100
  weight_decay: 0.01
  gradient_accumulation_steps: 8
  lora:
    r: 8       # LoRA rank
    alpha: 16   # LoRA alpha
    dropout: 0.1

# Audio processing
audio:
  sample_rate: 16000
  normalize: true
  
# Summarization
summarization:
  length:
    min: 50
    max: 500
  use_beam_search: false
  action_item_threshold: 0.7